### ISSUE TITLE
Commandの作り方

### ISSUE THREAD

**Issue by tao-s** [EC-CUBE/doc4.ec-cube.net#161]
無いから欲しい。
CSV吐き出すとか

**Comment by tao-s** [comment]
https://symfony.com/doc/4.4/console.html

**Comment by tao-s** [comment]
あった
http://localhost:4000/customize_symfony#command

**Comment by tao-s** [comment]
思い処理とかqueの作り方
https://symfony.com/doc/4.4/components/messenger.html

**Comment by ji-eunsoo** [comment]
@tao-s 
ありがとうございます。こちらはSymfonyのドキュメントを参照すればいいかなと思いますのでCloseします
