### ISSUE TITLE
EC-cube4.0.5を使っていますが、受注登録画面でその他明細が表示されないのですが、どうやって直せばいいですか？

### ISSUE THREAD

**Issue by yoyo0421** [EC-CUBE/doc4.ec-cube.net#214]
EC-cube4.0.5を使用しています。
管理画面の受注登録画面でその他明細のボタンはあるものの、ボタンを押しても何も表示されません。
お客様からの注文では手数料の計算は自動出来ているのですが、管理者による受注登録をする場合のみ、
登録ができません。
どのように直せばいいか教えていただけますでしょうか。

**Comment by kiy0taka** [comment]
@yoyo0421 こちら解決しましたでしょうか？修正やカスタマイズに関する質問は開発コミュニティにお願いします。
https://xoops.ec-cube.net/
