### ISSUE TITLE
インストールの間違い

### ISSUE THREAD

**Issue by entrycoderfox** [EC-CUBE/doc4.ec-cube.net#265]
## 概要(Overview)
[各種インストール方法](https://doc4.ec-cube.net/quickstart/install)にで、
「bin/console *」なとコマンドは欠失がある

例：
[ComposerからWebインストーラでインストールする](https://doc4.ec-cube.net/quickstart/composer_web_installer)
```
bin/console server:run
```
正しい方
```
php bin/console server:run
```

## 期待する内容(Expect)  or 要望 (Requirement)
[こち](https://github.com/entrycoderfox/doc4.ec-cube.net)からマージする。

### 環境 (environment)
+ EC-CUBE: 4.1.2
+ PHP: php-7.4.28-nts-Win32-vc15-x64
+ OS: Windows11 x64

**Comment by chihiro-adachi** [comment]
@entrycoderfox 
以下マージしました。ありがとうございます。
https://github.com/EC-CUBE/doc4.ec-cube.net/pull/268
https://github.com/EC-CUBE/doc4.ec-cube.net/pull/267
https://github.com/EC-CUBE/doc4.ec-cube.net/pull/266
