### ISSUE TITLE
head・body内にタグ設置機能が欲しい

### ISSUE THREAD

**Issue by Atsu0601** [EC-CUBE/doc4.ec-cube.net#308]
## 概要(Overview)
アナリティクスやGTMなどのタグを設置する機能をブロックを使用しないで
タグが動作するようにしていただきたいです。
ECの場合、MAツールの導入やその他計測タグの設置が多くなり、
基本機能として実装していただきたいです。

## 期待する内容(Expect)  or 要望 (Requirement)
アナリティクス・GTMは指定のIDを入力するだけで、タグが動作する様にしていただきたいです。
ブロック要素として設置するしか方法がない場合は、マニュアルなどに追記して頂きたいです。

## 備考
他のASPのECサービスでは、アナリティクスの設置する場合に、
管理画面の指定の箇所にタグのIDを入力する欄がありそこを入力することで、
タグが動作する仕様になっているものが多いです。
shopfiy・makeshop・future shopなど

**Comment by dotani1111** [comment]
@Atsu0601 
Issueありがとうございます。
GA4は4.3で対応予定です。
https://github.com/EC-CUBE/ec-cube/issues/4837
