### ISSUE TITLE
DEBUGモードの設定方法がほしい

### ISSUE THREAD

**Issue by chihiro-adachi** [EC-CUBE/doc4.ec-cube.net#46]
開発コミュニティや、勉強会などでよく説明する機会があるんですが、デバッグモードについて記述されているページがないような。

ここ見てくださいね、で誘導するだけ済むのでデバッグモードのコンテンツがあると助かります。

**Comment by Yangsin** [comment]
#69 にてマージされました、ご覧いただき不足点などあれば再度Issueいただけると助かります。
