### ISSUE TITLE
左メニューの項目名と、実際のページのタイトルが、食い違っている

### ISSUE THREAD

**Issue by ryo-endo** [EC-CUBE/doc4.ec-cube.net#84]
画像の通り、
・左メニューの項目名
・実際のページのタイトル
が、食い違っている。

![image](https://user-images.githubusercontent.com/16891862/79942424-c355c280-84a1-11ea-8885-e290cbcb6aeb.png)

## 期待
サイドメニューが「PurchaseFlow のカスタマイズ」。

## 修正箇所
このファイルを修正すれば良い
https://github.com/EC-CUBE/doc4.ec-cube.net/blob/master/_data/navigation.yml

**Comment by okazy** [comment]
「PurchaseFlow のカスタマイズ」と「カートのカスタマイズ」がはいっているので、ページ自体のタイトルは「購入フローのカスタマイズ」くらいがいいかと思いました。

**Comment by okazy** [comment]
あとトップページの文言修正もしたほうがいいですね。
https://github.com/EC-CUBE/doc4.ec-cube.net/blob/master/index.md

**Comment by Yangsin** [comment]
修正いただきましたので、クローズします。
