### ISSUE TITLE
プラグインのインストール失敗時の対処がわからない

### ISSUE THREAD

**Issue by naomi-himoto** [EC-CUBE/doc4.ec-cube.net#88]
プラグインのインストール失敗時の対処方法
ケースバイケースではあるものの、
主な失敗の原因と、試して見るべき対処方法

**Comment by ryo-endo** [comment]
こちらのQiitaの記事「EC-CUBE4系でのプラグインエラーの原因と対処法」を参考にしてみてください。(@nanasess さん記事ありがとうございます！)
https://qiita.com/nanasess/items/791c9ec98f69ada93ea0

公式ドキュメントにも記載すべき内容だと思うので、IssueはOPENにしておきます。

**Comment by naomi-himoto** [comment]
[@nanasess](https://github.com/nanasess) さんの記事を元に、一番多い原因であるキャッシュ問題に焦点を当て記載しました。詳しい対処法については、[@nanasess](https://github.com/nanasess) さんのご許可いただき、リンク掲載しております
