### ISSUE TITLE
GUIでのインストールが知りたい

### ISSUE THREAD

**Issue by naomi-himoto** [EC-CUBE/doc4.ec-cube.net#89]
XAMPPやMAMPなどを使ったGUIでのインストール方法と
OSの違いやPHP・DBの設定でのエラーや対処法

**Comment by okazy** [comment]
GUIでのインストール方法は需要ありそうですね。

各種エラーは上げるときりがないので、Q&Aみたいな形式で随時追加していけるような書き方がどうかと思いました。

**Comment by naomi-himoto** [comment]
WinはMAMPではうまくいかない
XAMPPのバージョンでphp7.4はNG ;
extension=php_intl.dllを編集
php.ini
max_execution_time=30 → 300など設定周りも記載

**Comment by Y-TSUMUKI** [comment]
Windows環境でXAMPPを使った方法は記載しました。

https://doc4.ec-cube.net/quickstart_install/gui_win_install

**Comment by okazy** [comment]
Windows向け、Mac向けのGUIインストールのページが追加されましたのでクローズします。
